# SPDX-License-Identifier: GPL-3.0-or-later
#
# PalmierOptionsManifest — emit the configured tree's `PALMIER_*` cache entries to
# `palmier_options.txt` (task 12.7; Requirements 16.7, 16.8).
#
# Requirement 16.7 asks the Verification_Suite to compare "the CMake option names
# stated in the documentation against the options defined by the build system".
# A test binary cannot ask CMake anything at run time, so the build system states
# its own option set once, here, at configure time — the only moment when the set
# is knowable — and the documentation checker reads that statement.
#
# Why the whole cache rather than a hand-maintained list: a list would be a THIRD
# place a new option has to be added (the option declaration, the documentation,
# the list), and the one most likely to be forgotten, which would make the check
# pass while the documentation is wrong. `get_cmake_property(CACHE_VARIABLES)`
# returns whatever the tree actually defined, so an option added tomorrow appears
# here tomorrow with no edit to this file, and the comparison against docs/BUILD.md
# fails until the documentation catches up. That is the intended failure.
#
# WHEN THIS MUST RUN. After every subdirectory has been added — `tests/` creates
# `PALMIER_PBT_MIN_SUCCESS`, and `cmake/PalmierDependencies.cmake` creates the six
# `PALMIER_*_AVAILABLE` internals — so the call site is the very END of the
# top-level CMakeLists.txt. Called earlier, the manifest would be missing entries
# and the checker would report them as undocumented options that the build system
# does not define, which is exactly backwards.
#
# FORMAT. One `NAME|TYPE` record per line; `#`-prefixed lines are comments and
# blank lines are ignored. TYPE is the cache entry's CMake type (BOOL, STRING,
# INTERNAL, ...), which is what lets the checker verify docs/BUILD.md's split
# between the user-settable table and the derived read-only (`INTERNAL`) table
# rather than only the names. Records are sorted, so the file is stable across
# configure runs and a diff of it is readable.

# Write the `PALMIER_*` cache manifest for the current tree to `output_path`.
function(palmier_write_options_manifest output_path)
    get_cmake_property(_palmier_cache_variables CACHE_VARIABLES)

    set(_palmier_records "")
    foreach(_name IN LISTS _palmier_cache_variables)
        if(NOT _name MATCHES "^PALMIER_")
            continue()
        endif()
        get_property(_type CACHE "${_name}" PROPERTY TYPE)
        if(NOT _type)
            # A cache entry created without a type reads back empty. Record it
            # under CMake's own name for that state rather than silently dropping
            # it: an untyped PALMIER_* entry is still an option the docs must
            # mention, and losing it here would weaken the comparison.
            set(_type "UNINITIALIZED")
        endif()
        list(APPEND _palmier_records "${_name}|${_type}")
    endforeach()

    list(SORT _palmier_records)
    list(LENGTH _palmier_records _count)

    set(_content
"# Generated by cmake/PalmierOptionsManifest.cmake at configure time. Do not edit.\n\
# The PALMIER_* cache entries this build tree defines, as NAME|TYPE records.\n\
# Read by the task 12.7 documentation consistency checker (Requirements 16.7, 16.8).\n\
# Entries: ${_count}\n")
    foreach(_record IN LISTS _palmier_records)
        string(APPEND _content "${_record}\n")
    endforeach()

    file(WRITE "${output_path}" "${_content}")
endfunction()
